name: heuristic
on: workflow_dispatch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.8'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion command-not-found cron debconf distro-info-data e2fsprogs fuse3 gettext-base hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1:amd64 libmecab2:amd64 libpam-runtime libpython3.8-minimal:amd64 libpython3.8-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace mailcap make man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-zope.interface python3.8-distutils python3.8-minimal rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget
          pip install importlib_metadata==8.5.0 importlib_resources==6.4.5
      - run: |
          make
      - run: |
          make ci
    env:
      ACCEPT_EULA: Y
      BOOTSTRAP_HASKELL_NONINTERACTIVE: '1'
      DEBIAN_FRONTEND: noninteractive
      DOTNET_MULTILEVEL_LOOKUP: '0'
      DOTNET_NOLOGO: '1'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650'
      HOMEBREW_NO_AUTO_UPDATE: '1'
      HOSTNAME: pop-os
      ImageOS: ubuntu22
      ImageVersion: 20250622.1.0
      LC_CTYPE: C.UTF-8
      MAKEFLAGS: ''
      MAKELEVEL: '1'
      MFLAGS: ''
      NETRC: ''
      POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions-ubuntu22
      PYTEST_VERSION: 8.3.5
      PYTHONNOUSERSITE: '1'
      SHLVL: '1'
      TERM: xterm
      _PYI_LINUX_PROCESS_NAME: sawra
      _PYI_PARENT_PROCESS_LEVEL: '1'
  no_chardet:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.8'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion command-not-found cron debconf distro-info-data e2fsprogs fuse3 gettext-base hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1:amd64 libmecab2:amd64 libpam-runtime libpython3.8-minimal:amd64 libpython3.8-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace mailcap make man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-zope.interface python3.8-distutils python3.8-minimal rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget
          pip install importlib_metadata==8.5.0 importlib_resources==6.4.5
      - run: |
          make
      - run: |
          python -m pip uninstall -y "charset_normalizer" "chardet"
      - run: |
          make ci
    env:
      ACCEPT_EULA: Y
      BOOTSTRAP_HASKELL_NONINTERACTIVE: '1'
      DEBIAN_FRONTEND: noninteractive
      DOTNET_MULTILEVEL_LOOKUP: '0'
      DOTNET_NOLOGO: '1'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650'
      HOMEBREW_NO_AUTO_UPDATE: '1'
      HOSTNAME: pop-os
      ImageOS: ubuntu22
      ImageVersion: 20250622.1.0
      LC_CTYPE: C.UTF-8
      MAKEFLAGS: ''
      MAKELEVEL: '1'
      MFLAGS: ''
      NETRC: ''
      POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions-ubuntu22
      PYTEST_VERSION: 8.3.5
      PYTHONNOUSERSITE: '1'
      SHLVL: '1'
      TERM: xterm
      _PYI_LINUX_PROCESS_NAME: sawra
      _PYI_PARENT_PROCESS_LEVEL: '1'
  urllib3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.8'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion command-not-found cron debconf distro-info-data e2fsprogs fuse3 gettext-base hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1:amd64 libmecab2:amd64 libpam-runtime libpython3.8-minimal:amd64 libpython3.8-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace mailcap make man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-zope.interface python3.8-distutils python3.8-minimal rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget
          pip install importlib_metadata==8.5.0 importlib_resources==6.4.5
      - run: |
          make
      - run: |
          python  -m pip install "urllib3<2"
      - run: |
          make ci
    env:
      ACCEPT_EULA: Y
      BOOTSTRAP_HASKELL_NONINTERACTIVE: '1'
      DEBIAN_FRONTEND: noninteractive
      DOTNET_MULTILEVEL_LOOKUP: '0'
      DOTNET_NOLOGO: '1'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650'
      HOMEBREW_NO_AUTO_UPDATE: '1'
      HOSTNAME: pop-os
      ImageOS: ubuntu22
      ImageVersion: 20250622.1.0
      LC_CTYPE: C.UTF-8
      MAKEFLAGS: ''
      MAKELEVEL: '1'
      MFLAGS: ''
      NETRC: ''
      POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions-ubuntu22
      PYTEST_VERSION: 8.3.5
      PYTHONNOUSERSITE: '1'
      SHLVL: '1'
      TERM: xterm
      _PYI_LINUX_PROCESS_NAME: sawra
      _PYI_PARENT_PROCESS_LEVEL: '1'
